runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /Sortable
  static_dir: Sortable
- url: /images
  static_dir: images
- url: /.*
  script: application.application
  secure: always


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
